name: ec2-instance-deploy
on:
  workflow_dispatch:
       inputs :
          aws-region-name:
             description: aws-region
             required: true
 
    
env:
  bucket: jatin-backend
  TFSTATE_FILE: jatin-bucket.tfstate
  
  aws-region: ${{github.event.inputs.aws-region-name}}

jobs:
  terraform_pipeline_deploy:
    name: terraform
    runs-on: ubuntu-latest

    
    steps:
    
      - uses: actions/checkout@v3
      - name: Setup terraform hashicorp
        uses: hashicorp/setup-terraform@v2 
        with:
          terraform_version: 1.3.4

        
      
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1   
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          Aws-region: ${{env.aws-region}}

      
      - name: terraform init  
        run: |
          cd ec2
          terraform init -reconfigure -backend-config="bucket=${{env.bucket}}" -backend-config="key=${{env.TFSTATE_FILE}}"
      
      - name: terraform plan
        run: |
          cd ec2
          terraform plan 
      - name: terraform apply  
      
        run: |
          cd ec2
          terraform apply -auto-approve
